---
- apt: upgrade=dist update_cache=yes
  sudo: yes
- apt: name=nginx-full state=present
  sudo: yes
- apt: name=git state=present
  sudo: yes
- apt: name=python-pip state=present
  sudo: yes
- name: clone let's encrypt from Github
  git: repo=https://github.com/letsencrypt/letsencrypt dest=/opt/letsencrypt/
  sudo: yes
- name: ensure letencrypt is installed
  command: /opt/letsencrypt/letsencrypt-auto --help
  sudo: yes