---
- name: install graphviz
  apt: name=graphviz state=present
  sudo: yes

- name: create /var/www directory
  file: path={{blog_dest}} state=directory mode=0770 group=www-data owner=www-data
  sudo: yes

- name: add the blog virtual server to nginx
  template: src=blog.conf dest=/etc/nginx/sites-enabled/ owner=www-data group=www-data mode=0644
  sudo: yes
  notify: restart nginx

- name: checkout the blog source from Github
  git: repo=https://github.com/jawher/jawher.me.git dest={{blog_src}}
  sudo: yes
  sudo_user: www-data

- name: install the required pip modules for the blog generator
  pip: requirements={{blog_src}}/requirements.txt
  sudo: yes

- name: create Pelican's output folder
  file: path={{blog_src}}/output state=directory
  sudo: yes
  sudo_user: www-data


- name: build the blog using Pelican
  shell: make clean html 2> build.log chdir={{blog_src}}
  sudo: yes
  sudo_user: www-data

- shell: cp -R {{blog_src}}/output/* /var/www/blog/
  sudo: yes
  sudo_user: www-data

- name: obtain or renew the blog TLS certificate
  command: /opt/letsencrypt/letsencrypt-auto --email "{{email}}" --agree-tos --renew-by-default certonly --webroot -w {{blog_dest}} -d {{blog_url}}
  sudo: true
  notify: restart nginx

- name: add TLS cert renewal cron job
  sudo: true
  cron: name="{{blog_url}} TLS cert renew" special_time="monthly" user="root" job="/opt/letsencrypt/letsencrypt-auto --email "{{email}}" --agree-tos --renew-by-default certonly --webroot -w {{blog_dest}} -d {{blog_url}} && service nginx reload"

