---
- name: add the gorex virtual server to nginx
  template: src=gorex-nginx.conf dest=/etc/nginx/sites-enabled/ owner=www-data group=www-data mode=0644
  sudo: yes
  notify: restart nginx
- name: copy the gorex exec
  copy: src=gorex_linux_amd64 dest=/usr/bin/  owner=root group=root mode=0755
  sudo: yes
- name: copy the gorex static files
  copy: src={{ item }} dest={{ gorex_dir }} owner=www-data group=www-data mode=0644
  sudo: yes
  with_items:
  - gorex.css
  - gorex.js
  - index.html
- name: make blog-builder an upstart service
  template: src=gorex.conf dest=/etc/init/ owner=root group=root mode=0644
  sudo: yes
  notify: reload services
- name: start the gorex service
  service: name=gorex state=restarted enabled=yes
  sudo: yes